# ============================================================
# CONFIGURATION AUTOMATIQUE DE GRAFANA
# ============================================================
# Configure automatiquement:
# - Datasource Prometheus
# - Dashboard MongoDB (ID 2583)
# ============================================================

resource "null_resource" "configure_grafana" {
  depends_on = [null_resource.install_monitoring]

  triggers = {
    monitoring_ip = aws_instance.monitoring.public_ip
    always_run    = timestamp()
  }

  provisioner "remote-exec" {
    connection {
      type        = "ssh"
      user        = "bigdata"
      private_key = file(local.private_key_file)
      host        = aws_instance.monitoring.public_ip
      timeout     = "5m"
    }

    inline = [
      "echo 'Configuration automatique de Grafana...'",
      "sleep 15",

      # Creer la datasource Prometheus via l'API Grafana
      "cat > /tmp/datasource.json << 'EOF'",
      "{",
      "  \"name\": \"Prometheus\",",
      "  \"uid\": \"prometheus\",",
      "  \"type\": \"prometheus\",",
      "  \"access\": \"proxy\",",
      "  \"url\": \"http://localhost:9090\",",
      "  \"isDefault\": true,",
      "  \"jsonData\": {",
      "    \"timeInterval\": \"5s\",",
      "    \"queryTimeout\": \"30s\",",
      "    \"httpMethod\": \"POST\"",
      "  }",
      "}",
      "EOF",

      # Forcer la suppression de l'ancienne datasource pour appliquer timeInterval=5s
      "curl -X DELETE http://admin:${var.grafana_admin_password}@localhost:3000/api/datasources/name/Prometheus 2>/dev/null || true",
      "sleep 2",

      "curl -X POST -H 'Content-Type: application/json' -d @/tmp/datasource.json http://admin:${var.grafana_admin_password}@localhost:3000/api/datasources 2>/dev/null || echo 'Datasource already exists'",

      # Telecharger le dashboard MongoDB depuis Grafana.com
      "echo 'Telechargement du dashboard MongoDB (ID: 2583)...'",
      "curl -s https://grafana.com/api/dashboards/2583/revisions/3/download -o /tmp/dashboard-2583.json",

      # Preparer le dashboard pour l'import
      "cat > /tmp/dashboard-import.json << 'EOF'",
      "{",
      "  \"dashboard\": $(cat /tmp/dashboard-2583.json),",
      "  \"overwrite\": true,",
      "  \"inputs\": [",
      "    {",
      "      \"name\": \"DS_PROMETHEUS\",",
      "      \"type\": \"datasource\",",
      "      \"pluginId\": \"prometheus\",",
      "      \"value\": \"Prometheus\"",
      "    }",
      "  ]",
      "}",
      "EOF",

      # Importer le dashboard
      "curl -X POST -H 'Content-Type: application/json' -d @/tmp/dashboard-import.json http://admin:${var.grafana_admin_password}@localhost:3000/api/dashboards/import 2>/dev/null && echo 'Dashboard MongoDB importe avec succes' || echo 'Erreur import dashboard'",

      # Creer un dashboard personnalise pour le projet
      # Metriques Percona mongodb_exporter v0.40 avec --collect-all et --mongodb.collstats-colls
      "cat > /tmp/custom-dashboard.json << 'EOF'",
      "{",
      "  \"dashboard\": {",
      "    \"title\": \"MongoDB Sharded Cluster - Overview\",",
      "    \"tags\": [\"mongodb\", \"sharding\"],",
      "    \"timezone\": \"browser\",",
      "    \"panels\": [",
      "      {",
      "        \"id\": 1,",
      "        \"title\": \"Total Documents (sensordb.readings)\",",
      "        \"type\": \"stat\",",
      "        \"datasource\": {\"type\": \"prometheus\", \"uid\": \"prometheus\"},",
      "        \"targets\": [",
      "          {",
      "            \"expr\": \"sum(max by (rs_nm) (mongodb_collstats_storageStats_count{database=\\\"sensordb\\\",collection=\\\"readings\\\"}))\",",
      "            \"refId\": \"A\",",
      "            \"legendFormat\": \"Total\"",
      "          }",
      "        ],",
      "        \"fieldConfig\": {\"defaults\": {\"unit\": \"short\", \"decimals\": 0}},",
      "        \"gridPos\": {\"h\": 8, \"w\": 8, \"x\": 0, \"y\": 0}",
      "      },",
      "      {",
      "        \"id\": 2,",
      "        \"title\": \"Documents par Shard\",",
      "        \"type\": \"piechart\",",
      "        \"datasource\": {\"type\": \"prometheus\", \"uid\": \"prometheus\"},",
      "        \"targets\": [",
      "          {",
      "            \"expr\": \"max by (rs_nm) (mongodb_collstats_storageStats_count{database=\\\"sensordb\\\",collection=\\\"readings\\\"})\",",
      "            \"legendFormat\": \"{{rs_nm}}\",",
      "            \"refId\": \"A\"",
      "          }",
      "        ],",
      "        \"options\": {\"legend\": {\"displayMode\": \"list\", \"placement\": \"bottom\", \"showLegend\": true, \"values\": [\"value\"]}, \"reduceOptions\": {\"calcs\": [\"lastNotNull\"]}},",
      "        \"gridPos\": {\"h\": 8, \"w\": 8, \"x\": 8, \"y\": 0}",
      "      },",
      "      {",
      "        \"id\": 3,",
      "        \"title\": \"Operations par Seconde (insert/query/update/delete)\",",
      "        \"type\": \"timeseries\",",
      "        \"datasource\": {\"type\": \"prometheus\", \"uid\": \"prometheus\"},",
      "        \"targets\": [",
      "          {",
      "            \"expr\": \"sum by (legacy_op_type) (rate(mongodb_ss_opcounters[30s]))\",",
      "            \"legendFormat\": \"{{legacy_op_type}}\",",
      "            \"refId\": \"A\",",
      "            \"interval\": \"5s\"",
      "          }",
      "        ],",
      "        \"fieldConfig\": {\"defaults\": {\"unit\": \"ops\"}},",
      "        \"gridPos\": {\"h\": 8, \"w\": 8, \"x\": 16, \"y\": 0}",
      "      },",
      "      {",
      "        \"id\": 4,",
      "        \"title\": \"Insertions par Shard (rate 30s)\",",
      "        \"type\": \"timeseries\",",
      "        \"datasource\": {\"type\": \"prometheus\", \"uid\": \"prometheus\"},",
      "        \"targets\": [",
      "          {",
      "            \"expr\": \"max by (rs_nm) (rate(mongodb_ss_opcounters{legacy_op_type=\\\"insert\\\"}[30s]))\",",
      "            \"legendFormat\": \"{{rs_nm}}\",",
      "            \"refId\": \"A\",",
      "            \"interval\": \"5s\"",
      "          }",
      "        ],",
      "        \"fieldConfig\": {\"defaults\": {\"unit\": \"ops\"}},",
      "        \"gridPos\": {\"h\": 8, \"w\": 12, \"x\": 0, \"y\": 8}",
      "      },",
      "      {",
      "        \"id\": 5,",
      "        \"title\": \"Connexions actives par Shard\",",
      "        \"type\": \"timeseries\",",
      "        \"datasource\": {\"type\": \"prometheus\", \"uid\": \"prometheus\"},",
      "        \"targets\": [",
      "          {",
      "            \"expr\": \"max by (rs_nm) (mongodb_ss_connections{conn_type=\\\"current\\\"})\",",
      "            \"legendFormat\": \"{{rs_nm}}\",",
      "            \"refId\": \"A\"",
      "          }",
      "        ],",
      "        \"gridPos\": {\"h\": 8, \"w\": 12, \"x\": 12, \"y\": 8}",
      "      },",
      "      {",
      "        \"id\": 6,",
      "        \"title\": \"Shard US (shard1RS)\",",
      "        \"type\": \"stat\",",
      "        \"datasource\": {\"type\": \"prometheus\", \"uid\": \"prometheus\"},",
      "        \"targets\": [",
      "          {",
      "            \"expr\": \"max(mongodb_collstats_storageStats_count{database=\\\"sensordb\\\",collection=\\\"readings\\\",rs_nm=\\\"shard1RS\\\"})\",",
      "            \"refId\": \"A\",",
      "            \"legendFormat\": \"docs\"",
      "          }",
      "        ],",
      "        \"fieldConfig\": {\"defaults\": {\"unit\": \"short\", \"decimals\": 0, \"color\": {\"mode\": \"fixed\", \"fixedColor\": \"blue\"}}},",
      "        \"options\": {\"colorMode\": \"background\", \"graphMode\": \"area\", \"textMode\": \"value\"},",
      "        \"gridPos\": {\"h\": 6, \"w\": 8, \"x\": 0, \"y\": 16}",
      "      },",
      "      {",
      "        \"id\": 7,",
      "        \"title\": \"Shard EU (shard2RS)\",",
      "        \"type\": \"stat\",",
      "        \"datasource\": {\"type\": \"prometheus\", \"uid\": \"prometheus\"},",
      "        \"targets\": [",
      "          {",
      "            \"expr\": \"max(mongodb_collstats_storageStats_count{database=\\\"sensordb\\\",collection=\\\"readings\\\",rs_nm=\\\"shard2RS\\\"})\",",
      "            \"refId\": \"A\",",
      "            \"legendFormat\": \"docs\"",
      "          }",
      "        ],",
      "        \"fieldConfig\": {\"defaults\": {\"unit\": \"short\", \"decimals\": 0, \"color\": {\"mode\": \"fixed\", \"fixedColor\": \"green\"}}},",
      "        \"options\": {\"colorMode\": \"background\", \"graphMode\": \"area\", \"textMode\": \"value\"},",
      "        \"gridPos\": {\"h\": 6, \"w\": 8, \"x\": 8, \"y\": 16}",
      "      },",
      "      {",
      "        \"id\": 8,",
      "        \"title\": \"Shard AP (shard3RS)\",",
      "        \"type\": \"stat\",",
      "        \"datasource\": {\"type\": \"prometheus\", \"uid\": \"prometheus\"},",
      "        \"targets\": [",
      "          {",
      "            \"expr\": \"max(mongodb_collstats_storageStats_count{database=\\\"sensordb\\\",collection=\\\"readings\\\",rs_nm=\\\"shard3RS\\\"})\",",
      "            \"refId\": \"A\",",
      "            \"legendFormat\": \"docs\"",
      "          }",
      "        ],",
      "        \"fieldConfig\": {\"defaults\": {\"unit\": \"short\", \"decimals\": 0, \"color\": {\"mode\": \"fixed\", \"fixedColor\": \"orange\"}}},",
      "        \"options\": {\"colorMode\": \"background\", \"graphMode\": \"area\", \"textMode\": \"value\"},",
      "        \"gridPos\": {\"h\": 6, \"w\": 8, \"x\": 16, \"y\": 16}",
      "      },",
      "      {",
      "        \"id\": 9,",
      "        \"title\": \"Evolution des documents par Shard\",",
      "        \"type\": \"timeseries\",",
      "        \"datasource\": {\"type\": \"prometheus\", \"uid\": \"prometheus\"},",
      "        \"targets\": [",
      "          {",
      "            \"expr\": \"max by (rs_nm) (mongodb_collstats_storageStats_count{database=\\\"sensordb\\\",collection=\\\"readings\\\"})\",",
      "            \"legendFormat\": \"{{rs_nm}}\",",
      "            \"refId\": \"A\"",
      "          }",
      "        ],",
      "        \"fieldConfig\": {\"defaults\": {\"unit\": \"short\", \"decimals\": 0, \"custom\": {\"drawStyle\": \"line\", \"lineWidth\": 2, \"fillOpacity\": 10}}},",
      "        \"gridPos\": {\"h\": 9, \"w\": 24, \"x\": 0, \"y\": 22}",
      "      }",
      "    ],",
      "    \"refresh\": \"5s\",",
      "    \"time\": {\"from\": \"now-5m\", \"to\": \"now\"},",
      "    \"timepicker\": {\"refresh_intervals\": [\"5s\", \"10s\", \"30s\", \"1m\", \"5m\"]},",
      "    \"schemaVersion\": 36,",
      "    \"version\": 1",
      "  },",
      "  \"overwrite\": true",
      "}",
      "EOF",

      "curl -X POST -H 'Content-Type: application/json' -d @/tmp/custom-dashboard.json http://admin:${var.grafana_admin_password}@localhost:3000/api/dashboards/db 2>/dev/null && echo 'Dashboard personnalise cree' || echo 'Erreur dashboard personnalise'",

      # Nettoyer les fichiers temporaires
      "rm -f /tmp/datasource.json /tmp/dashboard-*.json /tmp/custom-dashboard.json",

      "echo ''",
      "echo '====================================================================='",
      "echo 'GRAFANA CONFIGURE AUTOMATIQUEMENT'",
      "echo '====================================================================='",
      "echo ''",
      "echo 'Datasource Prometheus: OK'",
      "echo 'Dashboard MongoDB (ID 2583): OK'",
      "echo 'Dashboard personnalise: OK'",
      "echo ''",
      "echo 'Acces: http://${aws_instance.monitoring.public_ip}:3000'",
      "echo 'Login: admin'",
      "echo 'Password: ${var.grafana_admin_password}'",
      "echo ''"
    ]
  }
}
